name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: wget https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh -O ./gtk-osx-setup.sh
    - run: chmod u+x gtk-osx-setup.sh
    - run: export PATH="/Users/travis/.new_local/bin:$PATH"
    - run: export PIPENV_YES=1
    - run: ./gtk-osx-setup.sh
#     - run: jhbuild bootstrap-gtk-osx > build.log 2>&1 &
    - run: jhbuild bootstrap-gtk-osx
    - run: jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
