name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        sudo: false
    - name: Mangle Homebrew
      run: |
        sudo mv /usr/local/bin /usr/local/mangled-bin
        sudo mv /usr/local/include /usr/local/mangled-include
        sudo mv /usr/local/lib /usr/local/mangled-lib
        sudo mv /usr/local/etc /usr/local/mangled-etc
        sudo mv /usr/local/sbin /usr/local/mangled-sbin
        sudo mv /usr/local/share /usr/local/mangled-share
        sudo mv /usr/local/opt /usr/local/mangled-opt
    - name: Dowload setup script
      run: |
        curl -O https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh
        chmod u+x gtk-osx-setup.sh
    - name: Run setup script
      shell: bash --login --noprofile --norc -eo pipefail {0}
      run: |
        export PATH="$HOME/.new_local/bin:$PATH"
        export PIPENV_YES=1
        ./gtk-osx-setup.sh
        jhbuild bootstrap-gtk-osx
        jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
